### PR TITLE
Made some style changes and a fx for progress bars

### PR DESCRIPTION
**Pull request by johannpereze**
Hi Josh.
I really liked your Portfolio. Loved the color schema, the hero banner, and the animations.
I commented out the "height: 100vh" prop of the containers of the components. I think it adds too much empty space.
Also in the skills bars, I created a simple function to avoid repeating the styles too many times.
As a SEO rule, you should have just 1 h1 tag per page, so I changed the other ones to h2 tags.
Added different background colors to some sections to have visual separation.
And finally, I made some changes to the margins and padding so it looks better on mobile.
 
Some extra recommendations:
 
I know you just started with this project, so maybe you already considered some of these points, I’m just making assumptions about what I saw in the repo.
 
Vite is simpler and faster (like a lot lot faster) than Create React App. Today, I wouldn't start a project with CRA.
Configure a linter and code formatter. ESLint + Prettier are the most commonly used. It will make your code more legible and consistent.
Usually, it’s a better idea to have the CSS in separated files, so your component is not so much about styles but its business logic. And that makes the styles more reusable.
Try to use mapping functions instead of writing too much HTML. For example, you don’t need the HTML for 5 progress bars. You just need an object/array and a map function. We can talk about it if you want.
 
Hope you accept my PR or comment on it :D

### CODE REVIEW

**Comment by joshkotrous** [comment]
> Hi Josh. I really liked your Portfolio. Loved the color schema, the hero banner, and the animations. I commented out the "height: 100vh" prop of the containers of the components. I think it adds too much empty space. Also in the skills bars, I created a simple function to avoid repeating the styles too many times. As a SEO rule, you should have just 1 h1 tag per page, so I changed the other ones to h2 tags. Added different background colors to some sections to have visual separation. And finally, I made some changes to the margins and padding so it looks better on mobile.   Some extra recommendations:   I know you just started with this project, so maybe you already considered some of these points, I’m just making assumptions about what I saw in the repo.   Vite is simpler and faster (like a lot lot faster) than Create React App. Today, I wouldn't start a project with CRA. Configure a linter and code formatter. ESLint + Prettier are the most commonly used. It will make your code more legible and consistent. Usually, it’s a better idea to have the CSS in separated files, so your component is not so much about styles but its business logic. And that makes the styles more reusable. Try to use mapping functions instead of writing too much HTML. For example, you don’t need the HTML for 5 progress bars. You just need an object/array and a map function. We can talk about it if you want.   Hope you accept my PR or comment on it :D

Thank you so much for taking a look and leaving some feedback! Lots of helpful points in here of things I simply did not know. Very helpful tip on the SEO rules. I love what you did with the visual separation using different colors for each section and additional padding. The "height: 100vh" was a stylistic decision so I may go back and forth on leaving that in. 

Will look into Vite, had no idea this existed. 
Havent dug into any code formatters yet, thanks for this tip.
Good tip on keeping CSS in a separate files. I also like that using pure CSS makes using syntax such as ":hover" easier. For some reason I've had trouble using this syntax and others while storing styles within the .jsx files.

If my understanding is correct, the reason why we dont see much CSS in our professional projects is because we use MUI?

Definitely have worked with mapping functions before and as I refactor this project into smaller components will be applying that more.

Final question: 
Any resources you know of for best practices to follow in regards to margins and spacing? i.e. how did you know how to adjust the margins to make them look better?

**Comment by johannpereze** [comment]
I think we don't use CSS because we are not a Product Company, and clients usually want it to look just fine and to be functional and not too expensive, and MUI is great for that. If we were building something like Dinvy, where we get prospects to try our product, and wow them to convert them into customers, we would need a good UI/UX expert or even a team.
About the final question, I'm not an expert by any means, but some of the info was getting cut out on my phone screen because of the use of absolute values, so I just added some relative padding so content is always inside its container

I just enrolled in a [Udemy course](https://www.udemy.com/course/advanced-css-and-sass/) for CSS because I'm working on a personal project that will require a lot of styling. I'll let you know how it goes

WhatsApp Image 2022-08-22 at 9 24 08 PM

**Comment by joshkotrous** [comment]
> I think we don't use CSS because we are not a Product Company, and clients usually want it to look just fine and to be functional and not too expensive, and MUI is great for that. If we were building something like Dinvy, where we get prospects to try our product, and wow them to convert them into customers, we would need a good UI/UX expert or even a team. About the final question, I'm not an expert by any means, but some of the info was getting cut out on my phone screen because of the use of absolute values, so I just added some relative padding so content is always inside its container
> 
> I just enrolled in a [Udemy course](https://www.udemy.com/course/advanced-css-and-sass/) for CSS because I'm working on a personal project that will require a lot of styling. I'll let you know how it goes
> 
> WhatsApp Image 2022-08-22 at 9 24 08 PM

Understood, thanks! 

I was also thinking as I enhance this further to make my sections reusable. 

Since they all follow the same format i.e. a title with content inside. I was thinking to avoid code duplication, make management of spacing and margins easier, and creating new sections easier, I would create a generic Section component that would store the title and container styles and pass in the content of the section. I was thinking of accomplishing this in one of two ways:
1. Creating a Section class that would extend ReactComponent and each new Section would be an extension of the Section class (I dont know if this would even work, have yet to test it) 
2. Create a Section component that would pass in props for the title and the children

Any thoughts on the two approaches?

**Comment by johannpereze** [comment]
> > I think we don't use CSS because we are not a Product Company, and clients usually want it to look just fine and to be functional and not too expensive, and MUI is great for that. If we were building something like Dinvy, where we get prospects to try our product, and wow them to convert them into customers, we would need a good UI/UX expert or even a team. About the final question, I'm not an expert by any means, but some of the info was getting cut out on my phone screen because of the use of absolute values, so I just added some relative padding so content is always inside its container
> > I just enrolled in a [Udemy course](https://www.udemy.com/course/advanced-css-and-sass/) for CSS because I'm working on a personal project that will require a lot of styling. I'll let you know how it goes
> > WhatsApp Image 2022-08-22 at 9 24 08 PM
> 
> Understood, thanks!
> 
> I was also thinking as I enhance this further to make my sections reusable.
> 
> Since they all follow the same format i.e. a title with content inside. I was thinking to avoid code duplication, make management of spacing and margins easier, and creating new sections easier, I would create a generic Section component that would store the title and container styles and pass in the content of the section. I was thinking of accomplishing this in one of two ways:
> 
> 1. Creating a Section class that would extend ReactComponent and each new Section would be an extension of the Section class (I dont know if this would even work, have yet to test it)
> 2. Create a Section component that would pass in props for the title and the children
> 
> Any thoughts on the two approaches?

I usually use the second one. I create a component with all the styles and use it as a Higher Order Component (HOC), so it receives the title and children, and the return will be the component wrapping the children. I don't do classes in react, they're basically deprecated and the functional components solved a lot of problems classes had. I also think they're simpler and overall, better. Let me know if you have any more questions :)

**Comment by joshkotrous** [comment]
> > > I think we don't use CSS because we are not a Product Company, and clients usually want it to look just fine and to be functional and not too expensive, and MUI is great for that. If we were building something like Dinvy, where we get prospects to try our product, and wow them to convert them into customers, we would need a good UI/UX expert or even a team. About the final question, I'm not an expert by any means, but some of the info was getting cut out on my phone screen because of the use of absolute values, so I just added some relative padding so content is always inside its container
> > > I just enrolled in a [Udemy course](https://www.udemy.com/course/advanced-css-and-sass/) for CSS because I'm working on a personal project that will require a lot of styling. I'll let you know how it goes
> > > WhatsApp Image 2022-08-22 at 9 24 08 PM
> > 
> > 
> > Understood, thanks!
> > I was also thinking as I enhance this further to make my sections reusable.
> > Since they all follow the same format i.e. a title with content inside. I was thinking to avoid code duplication, make management of spacing and margins easier, and creating new sections easier, I would create a generic Section component that would store the title and container styles and pass in the content of the section. I was thinking of accomplishing this in one of two ways:
> > 
> > 1. Creating a Section class that would extend ReactComponent and each new Section would be an extension of the Section class (I dont know if this would even work, have yet to test it)
> > 2. Create a Section component that would pass in props for the title and the children
> > 
> > Any thoughts on the two approaches?
> 
> I usually use the second one. I create a component with all the styles and use it as a Higher Order Component (HOC), so it receives the title and children, and the return will be the component wrapping the children. I don't do classes in react, they're basically deprecated and the functional components solved a lot of problems classes had. I also think they're simpler and overall, better. Let me know if you have any more questions :)

Awesome! Will be going with the HOC approach. 

Closing this PR as Ive applied all of the feedback with the exception to Vite. Also added some animations to the menu drop down and scrolling animations while clicking links to headers. 

Thanks again for all of the feedback! It was super helpful in helping clean up my code, reducing code duplication, and got me to dig into fixing some other margin/padding issues with the Skills section. If you get some time to rereview my changes and suggest any other feedback that would be amazing!

**Pull request closed without merging**
